config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  get 'breed', to: 'breed#index'

  resources 'breed', only: %i[index] do
    post 'search', on: :collection
  end
  post 'reset', to: 'breed#reset'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flower_sentence.rb
class FlowerSentence < Taxonomy
end

app/models/plant.rb
class Plant < ApplicationRecord
end

app/models/seed_sentence.rb
class SeedSentence < Taxonomy
end

app/models/seeding_sentence.rb
class SeedingSentence < Taxonomy
end

app/models/taxonomy.rb
class Taxonomy < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/breed_controller.rb
class BreedController < ApplicationController
  def index
    @seed_sentences = SeedSentence.all
    @seeding_sentences = SeedingSentence.all
    @flower_sentences = FlowerSentence.all
    @user = User.find_by(name: "guest")
    @plant = Plant.find_by(seed_sen_id: @user.seed_sen_id, seeding_sen_id: @user.seeding_sen_id, flower_sen_id: @user.flower_sen_id)
  end

  def search
    @seed_sentences = SeedSentence.all
    @seeding_sentences = SeedingSentence.all
    @flower_sentences = FlowerSentence.all
    
    @user = User.find_by(name: "guest")
    
    if @user.seed_sen_id.nil? && @user.seeding_sen_id.nil? && @user.flower_sen_id.nil?
      @user.seed_sen_id = params[:sentence_id].to_i
      @user.save
      redirect_to breed_index_path
    elsif @user.seeding_sen_id.nil? && @user.flower_sen_id.nil?
      @user.seeding_sen_id = params[:sentence_id].to_i
      @user.save
      redirect_to breed_index_path
    elsif @user.flower_sen_id.nil?
      @user.flower_sen_id = params[:sentence_id].to_i
      @user.save
      redirect_to breed_index_path
    end
  end

  def reset
    @user = User.find_by(name: "guest")
    @user.seed_sen_id = nil
    @user.seeding_sen_id = nil
    @user.flower_sen_id = nil
    @user.save
    redirect_to breed_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/breed/_plant.html.erb
<%= plant.name %>
<%= button_to 'もう一度', reset_path, method: :post %>

app/views/breed/index.html.erb
<h1>育成画面</h1>
<% if @user.seed_sen_id.nil? && @user.seeding_sen_id.nil? && @user.flower_sen_id.nil? %>
  <%= render 'breed/sentences/seed_sentences', seed_sentences: @seed_sentences %>
<% elsif @user.seeding_sen_id.nil? && @user.flower_sen_id.nil? %>
  <%= render 'breed/sentences/seeding_sentences', seeding_sentences: @seeding_sentences %>
<% elsif @user.flower_sen_id.nil? %>
  <%= render 'breed/sentences/flower_sentences', flower_sentences: @flower_sentences %>
<% elsif !@user.seed_sen_id.nil? && !@user.seeding_sen_id.nil? && !@user.flower_sen_id.nil? %>
  <%= render 'breed/plant', plant: @plant %>
<% end %>

app/views/breed/sentences/_flower_sentences.html.erb
<% flower_sentences.each do |flower_sentence| %>
  <%= form_with url: search_breed_index_path, id: 'js-seed-sentence-button-to-seeding' do |f| %>
    <%= f.submit flower_sentence.sentence, class: 'btn btn-primary' %>
    <%= f.hidden_field :sentence_id, :value => flower_sentence.sentence_id %>
  <% end %>
  <br>
  <br>
<% end %>

app/views/breed/sentences/_seed_sentences.html.erb
<% seed_sentences.each do |seed_sentence| %>
  <%= form_with url: search_breed_index_path, id: 'js-seed-sentence-button-to-seeding' do |f| %>
    <%= f.submit seed_sentence.sentence, class: 'btn btn-primary' %>
    <%= f.hidden_field :sentence_id, :value => seed_sentence.sentence_id %>
  <% end %>
  <br>
  <br>
<% end %>

app/views/breed/sentences/_seeding_sentences.html.erb
<% seeding_sentences.each do |seeding_sentence| %>
  <%= form_with url: search_breed_index_path, id: 'js-seeding-sentence-button-to-flower' do |f| %>
    <%= f.submit seeding_sentence.sentence, class: 'btn btn-primary' %>
    <%= f.hidden_field :sentence_id, :value => seeding_sentence.sentence_id %>
  <% end %>
  <br>
  <br>
<% end %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>
<%= link_to 'はじめる', breed_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Plantbreed</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>